apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-bank
spec:
  selector:
    matchLabels:
      app: ms-bank
  template:
    metadata:
      labels:
        app: ms-bank
    spec:
      containers:
      - name: ms-bank
        image: ms-bank:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: spring.profiles.active
            value: prod
          - name: DATASOURCE_URL
            value: jdbc:mysql://service-db-bank:3306/bank
          - name: DATASOURCE_LOGIN
            value: root
          - name: DATASOURCE_PASSWORD
            value: root
          

# minikube docker-env
# eval $(minikube -p minikube docker-env)
#
# docker build -t ms-bank:1.0 .