apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-buyfeedback
spec:
  selector:
    matchLabels:
      app: ms-buyfeedback
  template:
    metadata:
      labels:
        app: ms-buyfeedback
    spec:
      containers:
      - name: ms-buyfeedback
        image: ms-buyfeedback:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: spring.profiles.active
            value: prod
          - name: spring.rabbitmq.host
            value: service-rabbitmq
          - name: spring.rabbitmq.username
            value: root
          - name: spring.rabbitmq.password
            value: root
          - name: spring.redis.host
            value: service-db-redis


# minikube docker-env
# eval $(minikube -p minikube docker-env)
#
# docker build -t ms-buyfeedback:1.0 .
