apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-redis
spec:
  selector:
    matchLabels:
      app: db-redis
  template:
    metadata:
      labels:
        app: db-redis
    spec:
      containers:
      - name: db-redis
        image: redis:alpine3.13
        ports:
        - containerPort: 6379