apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-buytrip
spec:
  selector:
    matchLabels:
      app: ms-buytrip
  template:
    metadata:
      labels:
        app: ms-buytrip
    spec:
      containers: 
      - name: ms-buytrip
        image: ms-buytrip:1.0
        ports:
          - containerPort: 8080
        env:
          - name: spring.profiles.active
            value: prod
          - name: spring.rabbitmq.host
            value: service-rabbitmq
          - name: spring.rabbitmq.username
            value: root
          - name: spring.rabbitmq.password
            value: root

# minikube docker-env
# eval $(minikube -p minikube docker-env)
#
# docker build -t ms-buytrip:1.0 .
